/* =========================
   ORIGINALDATEN (UNVERÄNDERT)
   ========================= */

const LEVEL1 = [
  { fr:"accepter", de:"akzeptieren" },
  { fr:"acheter", de:"kaufen" },
  { fr:"adorer", de:"lieben" },
  { fr:"aider", de:"helfen" },
  { fr:"aller en voiture", de:"mit dem Auto fahren" },
  { fr:"aller mal", de:"schlecht gehen" },
  { fr:"aller mieux", de:"besser gehen" },
  { fr:"aller à pied", de:"zu Fuß gehen" },
  { fr:"alors", de:"also" },
  { fr:"amusant / amusante", de:"lustig" },
  { fr:"après", de:"nach" },
  { fr:"arriver", de:"ankommen" },
  { fr:"arriver à l’heure", de:"pünktlich ankommen" },
  { fr:"assez de", de:"genug" },
  { fr:"attendre", de:"warten" },
  { fr:"attendre quelqu’un", de:"auf jemanden warten" },
  { fr:"au bout de", de:"am Ende von" },
  { fr:"au coin de", de:"an der Ecke von" },
  { fr:"au milieu de", de:"in der Mitte von" },
  { fr:"aujourd’hui", de:"heute" },
  { fr:"avant", de:"vor" },
  { fr:"avoir besoin de", de:"brauchen" },
  { fr:"avoir envie de", de:"Lust haben" },
  { fr:"avoir faim", de:"Hunger haben" },
  { fr:"avoir le temps", de:"Zeit haben" },
  { fr:"avoir mal", de:"Schmerzen haben" },
  { fr:"avoir mal à", de:"Schmerzen haben an" },
  { fr:"avoir soif", de:"Durst haben" },
  { fr:"beau / belle", de:"schön" },
  { fr:"beaucoup de", de:"viel(e)" },
  { fr:"bientôt", de:"bald" },
  { fr:"boire", de:"trinken" },
  { fr:"bon voyage", de:"gute Reise" },
  { fr:"c’est impossible", de:"das ist unmöglich" },
  { fr:"c’est possible", de:"das ist möglich" },
  { fr:"C’est trop cher.", de:"Das ist zu teuer." },
  { fr:"choisir", de:"auswählen" },
  { fr:"choisir un plat", de:"ein Gericht auswählen" },
  { fr:"commander", de:"bestellen" },
  { fr:"Comme ci, comme ça.", de:"So lala." },
  { fr:"consulter un médecin", de:"einen Arzt aufsuchen" },
  { fr:"content / contente", de:"zufrieden" },
  { fr:"continuer tout droit", de:"geradeaus weitergehen" },
  { fr:"D’accord.", de:"Einverstanden." },
  { fr:"demain", de:"morgen" },
  { fr:"dormir", de:"schlafen" },
  { fr:"décider", de:"entscheiden" },
  { fr:"déjà", de:"schon" },
  { fr:"délicieux / délicieuse", de:"lecker" },
  { fr:"détester", de:"hassen" },
  { fr:"en avance", de:"zu früh" },
  { fr:"en face de", de:"gegenüber von" },
  { fr:"en forme", de:"fit" },
  { fr:"encore", de:"noch" },
  { fr:"enfin", de:"schließlich" },
  { fr:"ensuite", de:"danach" },
  { fr:"entrer", de:"eintreten" },
  { fr:"environ", de:"ungefähr" },
  { fr:"essayer", de:"versuchen" },
  { fr:"faire attention", de:"aufpassen" },
  { fr:"faire de la musique", de:"Musik machen" },
  { fr:"faire du sport", de:"Sport treiben" },
  { fr:"fatigué / fatiguée", de:"müde" },
  { fr:"goûter", de:"probieren" },
  { fr:"grand / grande", de:"groß" },
  { fr:"habiter", de:"wohnen" },
  { fr:"heureux / heureuse", de:"glücklich" },
  { fr:"hier", de:"gestern" },
  { fr:"il fait beau", de:"es ist schön" },
  { fr:"Il fait beau aujourd’hui.", de:"Heute ist schönes Wetter." },
  { fr:"il fait chaud", de:"es ist warm" },
  { fr:"il fait froid", de:"es ist kalt" },
  { fr:"il fait mauvais", de:"es ist schlecht" },
  { fr:"il neige", de:"es schneit" },
  { fr:"il pleut", de:"es regnet" },
  { fr:"intéressant / intéressante", de:"interessant" },
  { fr:"inviter", de:"einladen" },
  { fr:"J’habite en ville.", de:"Ich wohne in der Stadt." },
  { fr:"jamais", de:"nie" },
  { fr:"Je fais du sport le week-end.", de:"Ich mache am Wochenende Sport." },
  { fr:"Je fais les courses.", de:"Ich gehe einkaufen." },
  { fr:"Je me couche tard.", de:"Ich gehe spät schlafen." },
  { fr:"Je me lève à sept heures.", de:"Ich stehe um sieben Uhr auf." },
  { fr:"Je pars de la maison.", de:"Ich verlasse das Haus." },
  { fr:"Je pense que", de:"ich denke, dass" },
  { fr:"Je prends le bus.", de:"Ich nehme den Bus." },
  { fr:"Je prends le petit-déjeuner.", de:"Ich frühstücke." },
  { fr:"Je rentre à la maison le soir.", de:"Ich komme abends nach Hause." },
  { fr:"Je suis fatigué(e).", de:"Ich bin müde." },
  { fr:"Je vis avec ma famille.", de:"Ich lebe mit meiner Familie." },
  { fr:"jouer", de:"spielen" },
  { fr:"jouer au basket", de:"Basketball spielen" },
  { fr:"jouer au foot", de:"Fußball spielen" },
  { fr:"les vacances", de:"die Ferien" }
];

/* =========================
   DEINE GESAMTLISTE (1:1 ÜBERNOMMEN)
   ========================= */

const LEVEL1_CHATLIST = [
  { fr:"Chouette, c’est la rentrée!", de:"Toll, es ist Schulanfang!" },
  { fr:"Zut, c’est la rentrée!", de:"Mist, es ist Schulanfang!" },

  { fr:"le livre", de:"das Buch" },
  { fr:"la règle", de:"das Lineal" },
  { fr:"le classeur", de:"der Ordner" },
  { fr:"le cahier", de:"das Heft" },
  { fr:"le crayon", de:"der Bleistift" },
  { fr:"le stylo", de:"der Kugelschreiber" },
  { fr:"la gomme", de:"der Radiergummi" },
  { fr:"le tableau noir", de:"die Wandtafel" },
  { fr:"la trousse", de:"das Etui" },
  { fr:"la table", de:"der Tisch" },
  { fr:"la chaise", de:"der Stuhl" },

  { fr:"la matière scolaire", de:"das Schulfach" },
  { fr:"l’école", de:"die Schule" },
  { fr:"l’allemand", de:"Deutsch" },
  { fr:"le français", de:"Französisch" },
  { fr:"l’anglais", de:"Englisch" },
  { fr:"les maths", de:"Mathematik" },
  { fr:"les mathématiques", de:"Mathematik" },

  { fr:"le jour", de:"der Tag" },
  { fr:"les jours de la semaine", de:"die Wochentage" },
  { fr:"lundi", de:"Montag" },
  { fr:"mardi", de:"Dienstag" },
  { fr:"mercredi", de:"Mittwoch" },
  { fr:"jeudi", de:"Donnerstag" },
  { fr:"vendredi", de:"Freitag" },
  { fr:"samedi", de:"Samstag" },
  { fr:"dimanche", de:"Sonntag" },

  { fr:"calculer", de:"rechnen" },
  { fr:"dessiner", de:"zeichnen" },
  { fr:"chanter", de:"singen" },
  { fr:"expérimenter", de:"experimentieren" },
  { fr:"parler français", de:"Französisch sprechen" },

  { fr:"la famille", de:"die Familie" },
  { fr:"l’enfant", de:"das Kind" },
  { fr:"la mère", de:"die Mutter / Mama" },
  { fr:"la maman", de:"die Mutter / Mama" },
  { fr:"le père", de:"der Vater / Papa" },
  { fr:"le papa", de:"der Vater / Papa" },
  { fr:"les parents", de:"die Eltern" },
  { fr:"la sœur", de:"die Schwester" },
  { fr:"le frère", de:"der Bruder" },
  { fr:"la grand-mère", de:"die Grossmutter" },
  { fr:"le grand-père", de:"der Grossvater" },
  { fr:"les grands-parents", de:"die Grosseltern" },
  { fr:"la tante", de:"die Tante" },
  { fr:"l’oncle", de:"der Onkel" },
  { fr:"la cousine", de:"die Cousine" },
  { fr:"le cousin", de:"der Cousin" },
  { fr:"le bébé", de:"das Baby" },
  { fr:"la fille", de:"die Tochter / das Mädchen" },
  { fr:"le fils", de:"der Sohn" },
  { fr:"le nom", de:"der Name" },
  { fr:"le prénom", de:"der Vorname" },
  { fr:"la langue", de:"die Sprache" },

  { fr:"voici", de:"hier ist / hier sind" },
  { fr:"voilà", de:"da ist / da sind" },
  { fr:"il est", de:"er/sie ist" },
  { fr:"elle est", de:"er/sie ist" },
  { fr:"ils sont", de:"sie sind" },
  { fr:"elles sont", de:"sie sind" },
  { fr:"c’est", de:"das ist" },
  { fr:"ce sont", de:"das sind" },

  { fr:"qui ?", de:"wer?" },
  { fr:"s’appeler", de:"heissen" },

  { fr:"la fiche personnelle", de:"der Steckbrief" },

  { fr:"parler", de:"sprechen" },
  { fr:"manger", de:"essen" },
  { fr:"nager", de:"schwimmen" },
  { fr:"commencer", de:"beginnen" },

  { fr:"l’acteur", de:"der Schauspieler" },
  { fr:"le cinéma muet", de:"der Stummfilm" },
  { fr:"marié", de:"verheiratet" },
  { fr:"mariée", de:"verheiratet" },
  { fr:"onze", de:"elf" },
  { fr:"le petit-fils", de:"der Enkel" },
  { fr:"la petite-fille", de:"die Enkelin" },
  { fr:"le chien", de:"der Hund" },
  { fr:"le chat", de:"die Katze" },
  { fr:"le membre de la famille", de:"das Familienmitglied" },
  { fr:"l’arbre", de:"der Baum" },
  { fr:"l’arbre généalogique", de:"der Stammbaum" },
  { fr:"le sexe", de:"das Geschlecht" },
  { fr:"l’âge", de:"das Alter" },
  { fr:"l’adresse", de:"die Adresse" },
  { fr:"le pays", de:"das Land" },
  { fr:"la signature", de:"die Unterschrift" },
  { fr:"le néerlandais", de:"Niederländisch" },
  { fr:"le suédois", de:"Schwedisch" },
  { fr:"l’italien", de:"Italienisch" },
  { fr:"l’espagnol", de:"Spanisch" },
  { fr:"le drapeau", de:"die Fahne" },

  { fr:"le loisir", de:"die Freizeitbeschäftigung" },
  { fr:"l’ordinateur", de:"der Computer" },
  { fr:"la télé", de:"der Fernseher" },
  { fr:"la console", de:"die Spielkonsole" },
  { fr:"l’animal", de:"das Tier / die Tiere" },
  { fr:"les animaux", de:"das Tier / die Tiere" },
  { fr:"le bricolage", de:"das Basteln" },
  { fr:"ma passion, c’est…", de:"meine Leidenschaft ist …" },
  { fr:"mon hobby, c’est…", de:"mein Hobby ist …" },
  { fr:"je suis fan de…", de:"ich bin Fan von …" },
  { fr:"le nombre", de:"die Zahl" },

  { fr:"l’élève", de:"der Schüler / die Schülerin" },
  { fr:"le garçon", de:"der Junge" },

  { fr:"danser", de:"tanzen" },
  { fr:"le foot", de:"Fussball" },
  { fr:"faire du foot", de:"Fussball spielen" },
  { fr:"le vélo", de:"das Fahrrad" },
  { fr:"faire du vélo", de:"Fahrrad fahren" },
  { fr:"le ski", de:"der Ski" },
  { fr:"faire du ski", de:"Ski fahren" },
  { fr:"l’unihockey", de:"Unihockey" },
  { fr:"faire de l’unihockey", de:"Unihockey spielen" },
  { fr:"la guitare", de:"die Gitarre" },
  { fr:"jouer de la guitare", de:"Gitarre spielen" },
  { fr:"la flûte", de:"die Flöte" },
  { fr:"le piano", de:"das Klavier" },
  { fr:"jouer du piano", de:"Klavier spielen" },
  { fr:"jouer dehors", de:"draussen spielen" },
  { fr:"écouter de la musique", de:"Musik hören" },
  { fr:"faire la cuisine", de:"kochen" },
  { fr:"faire du shopping", de:"einkaufen" },
  { fr:"rencontrer des amis", de:"Freunde treffen" },
  { fr:"aimer", de:"lieben / mögen" },
  { fr:"adorer", de:"sehr gern haben" },

  { fr:"les médias", de:"die Medien" },
  { fr:"la BD", de:"der Comic" },
  { fr:"le clip", de:"der Clip" },
  { fr:"la grimpe", de:"das Klettern" },
  { fr:"le tennis de table", de:"Tischtennis" },
  { fr:"le hockey sur glace", de:"Eishockey" },
  { fr:"la batterie", de:"das Schlagzeug" },
  { fr:"le violon", de:"die Geige" },
  { fr:"le cirque", de:"der Zirkus" },

  { fr:"la construction", de:"der Modellbau" },
  { fr:"mon sport favori", de:"mein Lieblingssport" },
  { fr:"l’équitation", de:"das Reiten" },
  { fr:"faire de l’équitation", de:"reiten" },
  { fr:"les acrobaties", de:"die Akrobatik" },
  { fr:"faire des acrobaties", de:"Akrobatik machen" },
  { fr:"la pêche", de:"das Fischen" },
  { fr:"pêcher", de:"angeln" },
  { fr:"les échecs", de:"Schach" },
  { fr:"jouer aux échecs", de:"Schach spielen" },
  { fr:"le théâtre", de:"das Theater" },
  { fr:"jouer du théâtre", de:"Theater spielen" },
  { fr:"être avec mes potes", de:"mit meinen Freunden sein" },
  { fr:"garder les enfants", de:"Kinder hüten" },
  { fr:"j’aime beaucoup", de:"ich mag sehr" },
  { fr:"détester", de:"hassen" },

  { fr:"l’ingrédient", de:"die Zutat" },
  { fr:"l’ananas", de:"die Ananas" },
  { fr:"le raisin", de:"die Traube" },
  { fr:"la fraise", de:"die Erdbeere" },
  { fr:"la banane", de:"die Banane" },
  { fr:"les nouilles", de:"die Nudeln" },
  { fr:"le champignon", de:"der Champignon" },
  { fr:"la carotte", de:"die Karotte" },
  { fr:"la poire", de:"die Birne" },
  { fr:"la tomate", de:"die Tomate" },
  { fr:"la soupe", de:"die Suppe" },

  { fr:"le corps", de:"der Körper" },
  { fr:"le visage", de:"das Gesicht" },
  { fr:"l’oreille", de:"das Ohr" },
  { fr:"les yeux", de:"die Augen" },
  { fr:"la tête", de:"der Kopf" },
  { fr:"le nez", de:"die Nase" },
  { fr:"la bouche", de:"der Mund" },

  { fr:"prendre", de:"nehmen" },
  { fr:"couper", de:"schneiden" },
  { fr:"poser", de:"legen" },
  { fr:"la lettre", de:"der Buchstabe" },

  { fr:"le loup", de:"der Wolf" },
  { fr:"l’abeille", de:"die Biene" },
  { fr:"la taille", de:"die Grösse" },
  { fr:"le poids", de:"das Gewicht" },
  { fr:"la nourriture", de:"die Nahrung" },

  { fr:"la couleur", de:"die Farbe" },
  { fr:"blanc", de:"weiss" },
  { fr:"blanche", de:"weiss" },
  { fr:"noir", de:"schwarz" },
  { fr:"noire", de:"schwarz" },
  { fr:"rouge", de:"rot" },
  { fr:"vert", de:"grün" },
  { fr:"verte", de:"grün" },
  { fr:"jaune", de:"gelb" },
  { fr:"bleu", de:"blau" },
  { fr:"bleue", de:"blau" },

  { fr:"la ville", de:"die Stadt" },
  { fr:"le monument", de:"das Bauwerk" },
  { fr:"la tour", de:"der Turm" },

  { fr:"le vêtement", de:"das Kleidungsstück" },
  { fr:"le tee-shirt", de:"das T-Shirt" },
  { fr:"le pull", de:"der Pullover" },
  { fr:"le pantalon", de:"die Hose" },
  { fr:"la robe", de:"das Kleid" },
  { fr:"la jupe", de:"der Rock" },
  { fr:"la veste", de:"die Jacke" },

  { fr:"faire les devoirs", de:"Hausaufgaben machen" },
  { fr:"à la maison", de:"zu Hause" },
  { fr:"à l’école", de:"in der Schule" },
  { fr:"dehors", de:"draussen" },

  { fr:"dormir", de:"schlafen" },
  { fr:"lire", de:"lesen" },

  { fr:"le matin", de:"der Morgen" },
  { fr:"le soir", de:"der Abend" },
  { fr:"la nuit", de:"die Nacht" },
  { fr:"le week-end", de:"das Wochenende" },

  { fr:"la maison", de:"das Haus" },
  { fr:"l’appartement", de:"die Wohnung" },
  { fr:"la cuisine", de:"die Küche" },
  { fr:"la chambre", de:"das Zimmer" },

  { fr:"monter", de:"steigen" },
  { fr:"boire", de:"trinken" },
  { fr:"manger", de:"essen" },
  { fr:"courir", de:"rennen" },

  { fr:"la vie", de:"das Leben" },
  { fr:"l’espoir", de:"die Hoffnung" },
  { fr:"le bonheur", de:"das Glück" },
  { fr:"le soleil", de:"die Sonne" },
  { fr:"la lune", de:"der Mond" },
  { fr:"l’amour", de:"die Liebe" },

  { fr:"heureux", de:"glücklich" },
  { fr:"heureuse", de:"glücklich" },
  { fr:"triste", de:"traurig" },
  { fr:"calme", de:"ruhig" },

  { fr:"l’histoire", de:"die Geschichte" },
  { fr:"l’accident", de:"der Unfall" },
  { fr:"la cloche", de:"die Glocke" },
  { fr:"sonner", de:"läuten" },

  { fr:"le meilleur ami", de:"der beste Freund" },
  { fr:"la meilleure amie", de:"die beste Freundin" },

  { fr:"la Terre", de:"die Erde" },
  { fr:"la planète", de:"der Planet" },
  { fr:"la mer", de:"das Meer" },
  { fr:"la montagne", de:"der Berg" },

  { fr:"le docteur", de:"der Arzt" },
  { fr:"le médecin", de:"der Arzt" },
  { fr:"être malade", de:"krank sein" },

  { fr:"le produit", de:"das Produkt" },
  { fr:"l’invention", de:"die Erfindung" },

  { fr:"un internat", de:"das Internat" },
  { fr:"une école de rêve", de:"eine Traumschule" },

  { fr:"à une heure et quart", de:"um Viertel nach eins" },
  { fr:"à deux heures et demie", de:"um halb drei" },
  { fr:"à quatre heures moins le quart", de:"um Viertel vor vier" },

  { fr:"ne … jamais", de:"nie" },
  { fr:"toujours", de:"immer" },
  { fr:"ne … plus", de:"nicht mehr" },
  { fr:"ne … rien", de:"nichts" },
  { fr:"tout le monde", de:"alle" },

  { fr:"un apprentissage", de:"die Berufslehre" },
  { fr:"le personnel", de:"das Personal" },
  { fr:"individuel", de:"individuell" },
  { fr:"individuelle", de:"individuell" },

  { fr:"Il est interdit de fumer.", de:"Rauchen ist verboten." },
  { fr:"Ce n’est pas une bonne idée.", de:"Das ist keine gute Idee." },
  { fr:"C’est vrai.", de:"Das stimmt." },
  { fr:"Je trouve ça dommage.", de:"Ich finde das schade." },

  { fr:"lire qc (à qn)", de:"etw. lesen (jdm.)" },
  { fr:"écrire qc à qn", de:"jdm. etw. schreiben" },
  { fr:"dire qc à qn", de:"jdm. etw. sagen" },
  { fr:"assez de", de:"genug von" }
];

/* =========================
   SPIELDATEN – AKTIV
   ========================= */
/* WICHTIG: Nichts geht verloren:
   DATA enthält 1) LEVEL1 (Original) + 2) LEVEL1_CHATLIST (deine Liste) */

const DATA = [...LEVEL1, ...LEVEL1_CHATLIST].map(item => ({
  prompt: item.de,
  target: [item.fr]
}));

/* =========================
   LEVEL2 BLEIBT UNBERÜHRT
   ========================= */

const LEVEL2 = [
  { fr:"j’ai", de:"avoir – 1re pers. sg." },
  { fr:"tu as", de:"avoir – 2e pers. sg." },
  { fr:"il a", de:"avoir – 3e pers. sg." },
  { fr:"elle a", de:"avoir – 3e pers. sg." },
  { fr:"nous avons", de:"avoir – 1re pers. pl." },
  { fr:"vous avez", de:"avoir – 2e pers. pl." },
  { fr:"ils ont", de:"avoir – 3e pers. pl." },
  { fr:"elles ont", de:"avoir – 3e pers. pl." }
];
